services:
  - type: web
    name: escalation-dashboard
    runtime: node
    buildCommand: npm install && npm install --prefix client && npm run build --prefix client
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 22.12.0
